/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dest */

#ifndef _Included_Dest
#define _Included_Dest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dest
 * Method:    dmsrcr_GIMP2
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Dest_dmsrcr_1GIMP2
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
